In [3]:
import torch
from torch.nn import functional as F

In [4]:
x_data = [0, 1, 0, 2, 3, 3]
x_tensor = torch.tensor(x_data)
x_tensor

tensor([0, 1, 0, 2, 3, 3])

In [5]:
x_one_hot = F.one_hot(x_tensor, 5)
x_one_hot

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0]])

In [6]:
torch.zeros(2,5, dtype=torch.int64)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [7]:
a = torch.tensor([1], dtype=torch.int64)

b = torch.Tensor([2])
a, b, a + b

(tensor([1]), tensor([2.]), tensor([3.]))

In [8]:
c = torch.zeros(3)
c.dtype

torch.float32

In [9]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [26]:
t = torch.tensor(dd)
y = t[:,0].reshape(3,1)
y.shape

torch.Size([3, 1])

In [7]:
a = torch.Tensor(123)
a.long().dtype

torch.int64

In [14]:
Y = torch.arange(40).reshape((2, 5, 4))
print(Y.shape)
Y = Y.reshape((-1, Y.shape[-1]))
print(Y.shape)

torch.Size([2, 5, 4])
torch.Size([10, 4])


In [15]:
import math
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

batch_size, num_steps = 32, 35
train_iter, vocab = d2l.load_data_time_machine(batch_size, num_steps)

In [18]:
i = 1
for X, Y in train_iter:
    if i ==1:
        print(X.shape, X)
        print(Y.shape, Y)
        i += 1


torch.Size([32, 35]) tensor([[ 9,  1, 18,  ...,  1,  8,  7],
        [ 3,  9,  4,  ...,  4,  8,  8],
        [ 6, 18,  2,  ...,  1,  9,  5],
        ...,
        [12,  1, 14,  ...,  6,  1,  4],
        [ 1,  3, 10,  ...,  2,  1,  4],
        [ 9,  2,  1,  ..., 10,  2, 17]])
torch.Size([32, 35]) tensor([[ 1, 18,  1,  ...,  8,  7,  1],
        [ 9,  4,  3,  ...,  8,  8,  2],
        [18,  2, 10,  ...,  9,  5,  8],
        ...,
        [ 1, 14,  8,  ...,  1,  4,  3],
        [ 3, 10,  4,  ...,  1,  4,  6],
        [ 2,  1, 20,  ...,  2, 17,  1]])
