In [1]:
import torch
from torch.nn import functional as F

In [57]:
x_data = [0, 1, 0, 2, 3, 3]
x_tensor = torch.tensor(x_data)
x_tensor

tensor([0, 1, 0, 2, 3, 3])

In [64]:
x_one_hot = F.one_hot(x_tensor, 5)
x_one_hot

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0]])

In [67]:
torch.zeros(2,5, dtype=torch.int64)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [78]:
a = torch.tensor([1], dtype=torch.int64)

b = torch.Tensor([2])
a, b, a + b

(tensor([1]), tensor([2.]), tensor([3.]))